# Generated by Django 3.1.4 on 2020-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='instrument',
            field=models.CharField(default='', max_length=100),
        ),
    ]
